#!/bin/sh

sdktools_url="https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip"
sdktools_filename="sdk-tools-linux-3859397.zip"
project_root="$( cd "$(dirname "$0")"; pwd -P )"


if [ -z "$1" ]
then
  echo "Usage: install_AndroidSDK.sh <install_path>"
  exit
fi

sdk_install_path="$(realpath $1)"

# Make directory for Android SDK
mkdir -p $sdk_install_path
cd $sdk_install_path

# Download Android SDK Tools
if [ ! -f $sdktools_filename ]; then
  echo "Downloading Android SDK Tools..."
  if ! wget -P . -q --show-progress $sdktools_url;
  then echo "Failed to download Android SDK Tools"; exit
  fi
fi

# unzip Android SDK Tools
echo "Extracting Android SDK Tools..."
if ! unzip $sdktools_filename;
then echo "Failed to unzip Android SDK Tools"; exit
fi

rm $sdktools_filename;

# update Android SDK packages
echo "Updating Android SDK packages..."
if ! ./tools/bin/sdkmanager --update --verbose;
then echo "Failed to update Android SDK Packages"; exit
fi

# set Android SDK path for Gradle build tool
echo "Configuring Android SDK path for Gradle..."
if ! echo "# File generated by install_AndroidSDK.sh script\n# Location of the SDK. This is only used by Gradle.\nsdk.dir=$sdk_install_path" > $project_root/client/local.properties;
then echo "Failed to set Android SDK path for Gradle";
fi

echo "Android SDK was installed in: $sdk_install_path"

exit





